BUFFER_SIZE = int(1e5)  # replay buffer size
BATCH_SIZE = 64  # minibatch size
GAMMA = 0.99  # discount factor
TAU = 1e-3  # for soft update of target parameters
LR = 5e-4  # learning rate
UPDATE_EVERY = 4  # how often to update the network
SEED = 0
DDQN = False  # use Double DQN or not
DUELING = True  # use Dueling network or not
DISTRIBUTIONAL = True  # use C51 or not